[workspace]
members = [ "eipw-lint", "eipw-lint-js" ]

[package]
name = "eipw"
description = "Ethereum Improvement Proposal linter that's one more than eipv"
version = "0.4.0"
edition = "2021"
license = "MPL-2.0"
rust-version = "1.65"
repository = "https://github.com/ethereum/eipw"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
annotate-snippets = "0.9.1"
tokio = { version = "1.25.0", features = [ "macros" ] }
clap = { version = "4.1.4", features = [ "derive" ] }
eipw-lint = { version = "0.4.0", path = "eipw-lint", features = [ "tokio" ] }
serde_json = "1.0.92"
thiserror = "1.0.37"

[target.'cfg(target_arch = "wasm32")'.dependencies]
tokio = { version = "1.25.0", features = [ "macros", "rt" ] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.25.0", features = [ "fs", "macros", "rt-multi-thread" ] }

[patch.crates-io.comrak]
git = "https://github.com/SamWilsn/comrak.git"
branch = "inline-line-numbers-0.16"

[patch.crates-io.jsonschema]
git = "https://github.com/SamWilsn/jsonschema-rs.git"
branch = "ahash-on-wasm"
